# Generated by Django 4.0.1 on 2022-01-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capital', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'countries',
            },
        ),
    ]
